targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":generators"
    import: "package:generators/generators.dart"
    builder_factories: ["generateHtmlfile"] #Builder name(BuilderOptions)
    build_extensions: { ".dart": [".html"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]